# Generated by Django 4.2.7 on 2024-01-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dav', '0002_alter_applications_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='audience',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
